spring:
  profiles: default

spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/kotring?serverTimezone=UTC
  username: kotring
  password: kotring

spring.jpa:
  hibernate:
    ddl-auto: validate
    use-new-id-generator-mappings: false

spring.jackson:
  property-naming-strategy: SNAKE_CASE

logging.level: error

logging.pattern.console: '%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr([%10.10t]){faint} %clr(%-40.40logger{39}){magenta} %clr(>){boldGreen} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'

custom.config.example: 'Do you see me?'

---

spring:
  profiles: prod

logging.file: 'application.log'
logging.file.max-history: 3

logging.pattern:
  console: # disabled
  file: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] %5p @ %-40.40logger{39} > %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
